name: Java CI without Maven or JDK setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check Java version
      run: java -version

    - name: Check javac version
      run: javac -version

    - name: Compile Java code (without JDK setup)
      run: javac -d out $(find . -name "*.java")

    - name: Run tests (without JDK setup)
      run: java -cp out org.junit.platform.console.ConsoleLauncher --scan-classpath
