name: Java GUI Program CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions에서 사용할 환경

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Navigate to project directory (if pom.xml is in a subdirectory)
        run: cd path/to/your/subdirectory  # 예: `cd subdir`로 변경

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
